// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1LAF2tNMfBBbueOTMaPLhVWcGIVblZyQ',
    appId: '1:911084598243:android:b90fc44a820ece4da866d6',
    messagingSenderId: '911084598243',
    projectId: 'pardnapp',
    storageBucket: 'pardnapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_udmnnOZCNRSiaMadiLJ2C3wBabzqiDU',
    appId: '1:911084598243:ios:5c3411205570364ea866d6',
    messagingSenderId: '911084598243',
    projectId: 'pardnapp',
    storageBucket: 'pardnapp.appspot.com',
    iosClientId: '911084598243-63spto1g72n22nane9nincdh37540r7i.apps.googleusercontent.com',
    iosBundleId: 'com.romaine.pardna',
  );
}
